name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.0
        with:
          hugo-version: "0.76.4"

      - name: Build
        run: hugo --gc --minify --cleanDestinationDir

  semver:
    runs-on: ubuntu-latest
    needs: [build]
    # Make sure to change this to f*&%*!*^ 'main' if needed.
    if: github.ref == 'refs/heads/main'

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: "refs/heads/main"
          fetch-depth: 0

      - name: Set up Python 3.8.*
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.*

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python_semantic_release
      - name: Configure Git
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
      - name: Semantic Release Publish
        run: |
          semantic-release publish -v DEBUG
